services:
  duplicati:
    container_name: duplicati
    image: duplicati/duplicati:latest
    restart: unless-stopped
    ports:
      - '8200:8200'
    volumes:
      - ${DATA_PATH}:/data
      - duplicati_config:/config
    environment:
      DUPLICATI__WEBSERVICE_PASSWORD: ${PASSWORD}
      DUPLICATI__WEBSERVICE_ALLOWED_HOSTNAMES: ${HOSTNAME}

volumes:
  duplicati_config:
